`timescale 1ns / 1ps
/* GOAL: Create a design that takes a clock generated by an FPGA and divides it.
 *
 * clkIn is the clock created from the Blackboard FPGA
 * clkOut is the slower, divided clock
 *
 * Created by: MorphoCH22
 * Board used: RealDigital Blackboard (Xilinx XC7007S ZYNQ)
 */

module ClockDivider(
        input clkIn,
        output clkOut
    );
    
    reg [23:0] cntr;
    
always @ (posedge(clkIn)) begin
    cntr = cntr + 1;
end

assign clkOut = (cntr == 16777215) ? 1'b1 : 1'b0;
    
endmodule
