/* GOAL: Create a design that allows the user to control two seven segment displays
 * that are common anode using a counter.
 *
 * dataIn refers to two sets of four switches that are used to represent two hexadecimal digits.
 * clk is the output generated by the counter which is used to switch between the two SSEG
 *      displays.
 *
 * In combination, the clk variable is used as a mux selector to send the upper or lower 4 bits
 *      of dataIn to a SSEG decoder, which displays on one of the digits determined by the counter.
 *
 *
 * Created by: MorphoCH22
 * Board used: RealDigital Blackboard (Xilinx XC7007S ZYNQ)
 */

module wrapper (
    input [7:0] dataIn,
    input clk,
    output [3:0] ssegctrl,
    output [6:0] sseg
);

wire [3:0] muxOut;
wire countSwitch;

Mux2to1 input_mux (
    .dataIn(dataIn),
    .switch(countSwitch),
    .dataOut(muxOut)
);

SSEG seven_seg (
    .data(muxOut),
    .display(sseg)
);

counter counter (
    .clk(clk),
    .Y(countSwitch),
    .ssegctrl(ssegctrl)
);

endmodule